import React, { useState, useRef, useEffect } from 'react';
import { Download, X, Share2, Copy, CheckCircle } from 'lucide-react';

export default function SnsShareGenerator({ visible, onClose, stats }) {
  const [regionName, setRegionName] = useState('');
  const [copied, setCopied] = useState(false);
  const canvasRef = useRef(null);

  const talked = stats.talked || 0;
  const flyers = (stats.flyer || 0) + (stats.station_flyer || 0);
  const speech = stats.speech || 0;
  const absent = stats.absent || 0;
  const total = talked + flyers + speech + absent;

  const drawCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    // Canvas size: 1080x1920 (9:16 vertical)
    canvas.width = 1080;
    canvas.height = 1920;
    
    // Background gradient (PoliStep Brand Colors)
    const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
    gradient.addColorStop(0, '#0F172A'); // Slate-900
    gradient.addColorStop(1, '#064E3B'); // Emerald-900
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Decorative circles
    ctx.fillStyle = 'rgba(16, 185, 129, 0.1)'; // Emerald-500 with opacity
    ctx.beginPath();
    ctx.arc(900, 300, 400, 0, Math.PI * 2);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(100, 1600, 600, 0, Math.PI * 2);
    ctx.fill();

    // Texts
    ctx.textAlign = 'center';
    
    // Header
    ctx.fillStyle = '#10B981';
    ctx.font = 'bold 50px sans-serif';
    ctx.fillText('TODAY\'S REPORT', canvas.width / 2, 250);
    
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 90px sans-serif';
    ctx.fillText('本日のドブ板活動', canvas.width / 2, 380);

    if (regionName) {
      ctx.fillStyle = '#94A3B8';
      ctx.font = 'bold 50px sans-serif';
      ctx.fillText(`📍 ${regionName}周辺`, canvas.width / 2, 500);
    }

    // Stats Box
    const boxY = 650;
    ctx.fillStyle = 'rgba(255, 255, 255, 0.1)';
    ctx.roundRect = function (x, y, w, h, r) {
      if (w < 2 * r) r = w / 2;
      if (h < 2 * r) r = h / 2;
      this.beginPath();
      this.moveTo(x+r, y);
      this.arcTo(x+w, y,   x+w, y+h, r);
      this.arcTo(x+w, y+h, x,   y+h, r);
      this.arcTo(x,   y+h, x,   y,   r);
      this.arcTo(x,   y,   x+w, y,   r);
      this.closePath();
      return this;
    }
    ctx.roundRect(140, boxY, 800, 650, 40).fill();

    // Stats Grid
    ctx.textAlign = 'left';
    ctx.fillStyle = '#E2E8F0';
    ctx.font = 'bold 55px sans-serif';
    
    ctx.fillText('🤝 対話できた数', 220, boxY + 120);
    ctx.fillText('📄 ビラ・チラシ配布', 220, boxY + 270);
    ctx.fillText('🎤 街頭演説', 220, boxY + 420);
    ctx.fillText('🏃‍♂️ 総アクション数', 220, boxY + 570);

    ctx.textAlign = 'right';
    ctx.fillStyle = '#FCD34D'; // Yellow-300 for numbers
    ctx.font = 'bold 70px sans-serif';
    ctx.fillText(`${talked} 件`, 860, boxY + 120);
    ctx.fillText(`${flyers} 枚`, 860, boxY + 270);
    ctx.fillText(`${speech} 回`, 860, boxY + 420);
    ctx.fillText(`${total} 回`, 860, boxY + 570);

    // Sub message
    ctx.textAlign = 'center';
    ctx.font = 'bold 50px sans-serif';
    ctx.fillStyle = '#FFFFFF';
    ctx.fillText('皆様の温かいお言葉、ありがとうございます。', canvas.width / 2, 1450);
    ctx.fillText('引き続き地域のために活動してまいります！', canvas.width / 2, 1550);
    
    // Draw Logo
    const logoImg = new Image();
    logoImg.onload = () => {
      const logoSize = 120;
      ctx.drawImage(logoImg, canvas.width / 2 - logoSize / 2, 1680, logoSize, logoSize);
      ctx.font = '35px sans-serif';
      ctx.fillStyle = '#94A3B8';
      ctx.fillText('Generated by PoliStep', canvas.width / 2, 1850);
    };
    logoImg.src = '/polistep_logo_new.jpg';
  };

  useEffect(() => {
    if (visible) {
      // Small delay to ensure canvas is rendered
      setTimeout(drawCanvas, 100);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible, regionName, stats]);

  if (!visible) return null;

  const handleDownload = () => {
    const canvas = canvasRef.current;
    if (canvas) {
      const link = document.createElement('a');
      link.download = `polistep_activity_${new Date().toISOString().split('T')[0]}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    }
  };

  const shareText = `本日も${regionName || '地域'}を回らせていただきました！🏃‍♂️\n\n🎯 本日の活動実績\n🤝 対話できた数: ${talked}件\n📄 ビラ配布: ${flyers}枚\n🎤 街頭演説: ${speech}回\n\n貴重なご意見をいただき、ありがとうございます。引き続き地域のために走り抜きます！\n#ドブ板活動 #PoliStep`;

  const handleCopy = () => {
    navigator.clipboard.writeText(shareText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="overlay">
      <div className="modal-content" style={{ maxWidth: '600px', width: '95%', padding: '2rem', textAlign: 'left', maxHeight: '95vh', overflowY: 'auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 900, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Share2 size={24} color="#10B981" /> SNS用活動報告を作成
          </h3>
          <button onClick={onClose} style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}><X size={24} color="#64748B" /></button>
        </div>
        
        <p style={{ color: '#475569', fontSize: '0.95rem', marginBottom: '1.5rem', lineHeight: 1.6 }}>
          日々の努力（活動量）を有権者に分かりやすく伝えるための、スタイリッシュなインフォグラフィック画像と投稿文章を生成します。
        </p>

        <div style={{ marginBottom: '1.5rem' }}>
          <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem', color: '#1E293B' }}>📍 活動した地域名（任意）</label>
          <input 
            type="text" 
            placeholder="例: 中野区弥生町" 
            value={regionName}
            onChange={(e) => setRegionName(e.target.value)}
            className="input-premium"
          />
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', marginTop: '2rem' }}>
          
          {/* 画像セクション */}
          <div style={{ background: '#F8FAFC', padding: '1.5rem', borderRadius: '16px', border: '1px solid #E2E8F0', textAlign: 'center' }}>
            <p style={{ fontWeight: 'bold', marginBottom: '1rem', color: '#0F172A', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
               ① 画像を保存する
            </p>
            <div style={{ border: '1px solid #CBD5E1', borderRadius: '12px', overflow: 'hidden', margin: '0 auto 1.5rem', maxWidth: '240px', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}>
              <canvas ref={canvasRef} style={{ width: '100%', height: 'auto', display: 'block' }}></canvas>
            </div>
            <button onClick={handleDownload} className="btn-premium" style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', background: '#1D4ED8', width: '100%' }}>
              <Download size={20} /> 画像をダウンロード
            </button>
          </div>

          {/* テキストセクション */}
          <div style={{ background: '#F8FAFC', padding: '1.5rem', borderRadius: '16px', border: '1px solid #E2E8F0' }}>
            <p style={{ fontWeight: 'bold', marginBottom: '1rem', color: '#0F172A', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
               ② 文章をコピーする
            </p>
            <div style={{ position: 'relative' }}>
              <textarea 
                value={shareText} 
                readOnly 
                style={{ width: '100%', height: '180px', padding: '1rem', borderRadius: '12px', border: '1px solid #CBD5E1', background: 'white', color: '#334155', fontSize: '0.95rem', lineHeight: 1.6, resize: 'none' }}
              />
              <button 
                onClick={handleCopy}
                style={{ position: 'absolute', bottom: '10px', right: '10px', background: copied ? '#10B981' : '#1E293B', color: 'white', border: 'none', padding: '0.5rem 1rem', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontWeight: 'bold', transition: 'all 0.2s' }}
              >
                {copied ? <CheckCircle size={16} /> : <Copy size={16} />}
                {copied ? 'コピーしました！' : 'コピー'}
              </button>
            </div>
            <p style={{ color: '#64748B', fontSize: '0.85rem', marginTop: '0.75rem', textAlign: 'center' }}>
              コピーした文章は、SNS投稿画面で自由に編集してご使用ください。
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}
