import React, { useState, useRef, useEffect } from 'react';
import { Camera, Download, X, Share2 } from 'lucide-react';

export default function SnsShareGenerator({ visible, onClose, stats }) {
  const [regionName, setRegionName] = useState('');
  const [photo, setPhoto] = useState(null);
  const canvasRef = useRef(null);

  useEffect(() => {
    if (visible && photo && regionName) {
      drawCanvas();
    }
  }, [visible, photo, regionName, stats]);

  if (!visible) return null;

  const totalGreetings = (stats.talked || 0) + (stats.absent || 0) + (stats.flyer || 0) + (stats.speech || 0) + (stats.station_flyer || 0);

  const handlePhotoUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setPhoto(event.target.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const drawCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    // Canvas size: 1080x1920 (9:16 vertical)
    canvas.width = 1080;
    canvas.height = 1920;
    
    const bgImg = new Image();
    bgImg.onload = () => {
      // Draw background image filling the canvas (cover)
      const scale = Math.max(canvas.width / bgImg.width, canvas.height / bgImg.height);
      const x = (canvas.width / 2) - (bgImg.width / 2) * scale;
      const y = (canvas.height / 2) - (bgImg.height / 2) * scale;
      ctx.drawImage(bgImg, x, y, bgImg.width * scale, bgImg.height * scale);
      
      // Draw dark overlay for text readability
      ctx.fillStyle = 'rgba(15, 23, 42, 0.6)';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      // Draw texts
      ctx.textAlign = 'center';
      
      // Header
      ctx.fillStyle = '#10B981';
      ctx.font = 'bold 50px sans-serif';
      ctx.fillText('TODAY\'S ACTIVITY', canvas.width / 2, 300);
      
      // Main Message
      ctx.fillStyle = '#FFFFFF';
      ctx.font = 'bold 80px sans-serif';
      ctx.fillText(`本日は${regionName}周辺で、`, canvas.width / 2, 500);
      
      ctx.font = 'bold 120px sans-serif';
      ctx.fillStyle = '#FCD34D';
      ctx.fillText(`${totalGreetings}軒`, canvas.width / 2, 700);
      
      ctx.font = 'bold 70px sans-serif';
      ctx.fillStyle = '#FFFFFF';
      ctx.fillText(`のお宅にご挨拶させていただきました！`, canvas.width / 2, 850);
      
      // Sub message
      ctx.font = '50px sans-serif';
      ctx.fillStyle = '#E2E8F0';
      ctx.fillText('皆様の温かいお言葉、ありがとうございます。', canvas.width / 2, 1050);
      ctx.fillText('引き続き地域のために活動してまいります！', canvas.width / 2, 1150);
      
      // Draw Logo
      const logoImg = new Image();
      logoImg.onload = () => {
        // Logo size 200x200
        const logoSize = 150;
        ctx.drawImage(logoImg, canvas.width / 2 - logoSize / 2, 1600, logoSize, logoSize);
        
        ctx.font = '40px sans-serif';
        ctx.fillStyle = '#FFFFFF';
        ctx.fillText('Generated by PoliStep', canvas.width / 2, 1800);
      };
      logoImg.src = '/polistep_logo_new.jpg';
    };
    bgImg.src = photo;
  };

  const handleDownload = () => {
    const canvas = canvasRef.current;
    if (canvas) {
      const link = document.createElement('a');
      link.download = `polistep_activity_${new Date().toISOString().split('T')[0]}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    }
  };

  return (
    <div className="overlay">
      <div className="modal-content" style={{ maxWidth: '500px', padding: '2rem', textAlign: 'left', maxHeight: '90vh', overflowY: 'auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 900, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Share2 size={24} color="#10B981" /> 本日の活動報告を作成
          </h3>
          <button onClick={onClose} style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}><X size={24} color="#64748B" /></button>
        </div>
        
        <p style={{ color: '#475569', fontSize: '0.9rem', marginBottom: '1.5rem', lineHeight: 1.6 }}>
          SNS（InstagramストーリーやXなど）に投稿するための縦長画像を自動生成します。「選挙」や「投票依頼」といった文言を含まない、クリーンな政治活動報告の形式になります。
        </p>

        <div style={{ marginBottom: '1.5rem' }}>
          <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem', color: '#1E293B' }}>📍 活動した地域名</label>
          <input 
            type="text" 
            placeholder="例: 中野区弥生町" 
            value={regionName}
            onChange={(e) => setRegionName(e.target.value)}
            className="input-premium"
          />
        </div>

        <div style={{ marginBottom: '1.5rem' }}>
          <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem', color: '#1E293B' }}>📸 活動の様子の写真（背景になります）</label>
          <label style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', padding: '1rem', background: '#F1F5F9', border: '2px dashed #CBD5E1', borderRadius: '12px', cursor: 'pointer', color: '#475569', fontWeight: 'bold' }}>
            <Camera size={20} /> 写真を選択
            <input type="file" accept="image/*" onChange={handlePhotoUpload} style={{ display: 'none' }} />
          </label>
        </div>

        {photo && regionName ? (
          <div style={{ marginTop: '2rem', textAlign: 'center' }}>
            <p style={{ fontWeight: 'bold', marginBottom: '0.5rem', color: '#10B981' }}>✨ 画像が生成されました！</p>
            <div style={{ border: '4px solid #E2E8F0', borderRadius: '16px', overflow: 'hidden', margin: '0 auto 1.5rem', maxWidth: '270px' }}>
              <canvas ref={canvasRef} style={{ width: '100%', height: 'auto', display: 'block' }}></canvas>
            </div>
            <button onClick={handleDownload} className="btn-premium" style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', background: '#1D4ED8' }}>
              <Download size={20} /> 画像を保存する
            </button>
          </div>
        ) : (
          <div style={{ marginTop: '2rem', padding: '2rem', textAlign: 'center', background: '#F8FAFC', borderRadius: '12px', border: '1px solid #E2E8F0', color: '#94A3B8' }}>
            地域名を入力し、写真を選択すると<br/>プレビューが表示されます。
          </div>
        )}
      </div>
    </div>
  );
}
